package com.pg2.tetris;

import javafx.animation.AnimationTimer;
import javafx.geometry.*;
import javafx.scene.canvas.*;
import javafx.scene.control.*;
import javafx.scene.input.KeyCode;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.text.*;
import java.util.*;

/** View in MVC. It renders model state and delegates game actions to controllers. */
public final class GamePane extends BorderPane {
    private final GameSettings settings; private final Runnable onBack;
    private final List<PlayerView> players=new ArrayList<>();
    private final Map<KeyCode,GameCommand> commands=new EnumMap<>(KeyCode.class);
    private final Label status=new Label(); private AnimationTimer timer; private long lastFrame;
    public GamePane(GameSettings settings,Runnable onBack){this.settings=settings;this.onBack=onBack;PieceSequence shared=new PieceSequence();players.add(new PlayerView("Player 1",settings.getPlayerOneType(),shared));if(settings.isExtendedMode())players.add(new PlayerView("Player 2",settings.getPlayerTwoType(),shared));build();configureCommands();startLoop();}
    private void build(){Button back=new Button("Back");back.setOnAction(e->{stop();onBack.run();});Label title=new Label("TETRIS");title.getStyleClass().add("game-title");HBox header=new HBox(20,back,title,status);header.setAlignment(Pos.CENTER);header.setPadding(new Insets(8));HBox boards=new HBox(18);boards.setAlignment(Pos.CENTER);players.forEach(p->boards.getChildren().add(p.root));Label help=new Label(players.size()>1?"P1: arrows/Space   P2: A/D/W/C/X   P pause   M music   S sound":"Arrows/Space   P pause   M music   S sound");setTop(header);setCenter(boards);setBottom(help);BorderPane.setAlignment(help,Pos.CENTER);setPadding(new Insets(10));getStyleClass().add("game-root");setFocusTraversable(true);}
    private void configureCommands(){if(players.get(0).type==PlayerType.HUMAN){GameController one=players.get(0).controller;commands.put(KeyCode.LEFT,one::moveLeft);commands.put(KeyCode.RIGHT,one::moveRight);commands.put(KeyCode.UP,one::rotateClockwise);commands.put(KeyCode.DOWN,one::softDrop);commands.put(KeyCode.SPACE,one::hardDrop);}if(players.size()>1&&players.get(1).type==PlayerType.HUMAN){GameController two=players.get(1).controller;commands.put(KeyCode.A,two::moveLeft);commands.put(KeyCode.D,two::moveRight);commands.put(KeyCode.W,two::rotateClockwise);commands.put(KeyCode.C,two::softDrop);commands.put(KeyCode.X,two::hardDrop);}setOnKeyPressed(e->{if(e.getCode()==KeyCode.P)players.forEach(p->p.controller.togglePause());else if(e.getCode()==KeyCode.M){settings.setMusic(AudioManager.getInstance().toggleMusic());SettingsManager.getInstance().save();status.setText("Music: "+(settings.isMusic()?"on":"off"));}else if(e.getCode()==KeyCode.S){settings.setSoundEffects(AudioManager.getInstance().toggleSound());SettingsManager.getInstance().save();status.setText("Sound: "+(settings.isSoundEffects()?"on":"off"));}else{GameCommand c=commands.get(e.getCode());if(c!=null)c.execute();}players.forEach(PlayerView::render);e.consume();});}
    private void startLoop(){timer=new AnimationTimer(){public void handle(long now){if(lastFrame==0)lastFrame=now;double dt=Math.min(.05,(now-lastFrame)/1e9);lastFrame=now;players.forEach(p->p.update(dt));}};timer.start();requestFocus();}
    public void stop(){if(timer!=null)timer.stop();players.forEach(PlayerView::close);}
    private final class PlayerView implements GameEventListener {
        final String name;final PlayerType type;final GameController controller;final PlayerStrategy strategy;final Canvas canvas;final Label stats=new Label();final VBox root;ExternalPlayerClient external;Tetromino externalPiece;Integer externalTargetRotation;Integer externalTargetColumn;double externalActionDelay;
        PlayerView(String name,PlayerType type,PieceSequence shared){this.name=name;this.type=type;controller=new GameController(settings,this,shared,new TetrominoFactory());strategy=type==PlayerType.AI?new AiStrategy():new HumanStrategy();double cell=Math.min(25,Math.min(340.0/settings.getFieldWidth(),560.0/settings.getFieldHeight()));canvas=new Canvas(settings.getFieldWidth()*cell,settings.getFieldHeight()*cell);root=new VBox(5,new Label(name+" - "+type),stats,canvas);root.setAlignment(Pos.CENTER);if(type==PlayerType.EXTERNAL){external=new ExternalPlayerClient(this::applyExternalMove,connected->status.setText(connected?name+" connected":name+" waiting for server..."));external.start();requestExternalMove();}updateLabels();render();}
        void update(double dt){controller.update(dt);strategy.update(controller,dt);if(type==PlayerType.EXTERNAL){if(controller.getCurrentPiece()!=externalPiece)requestExternalMove();advanceExternalMove(dt);}render();}
        void updateLabels(){stats.setText("Level "+controller.getLevel()+"  Score "+controller.getScore()+"  Lines "+controller.getLines());}
        void requestExternalMove(){externalPiece=controller.getCurrentPiece();externalTargetRotation=null;externalTargetColumn=null;externalActionDelay=.40;if(externalPiece==null||external==null)return;GameBoard board=controller.getBoard();int[][] cells=new int[board.getRows()][board.getColumns()];for(int r=0;r<board.getRows();r++)for(int c=0;c<board.getColumns();c++)cells[r][c]=board.getCell(r,c)==null?0:1;external.requestMove(new ExternalPlayerClient.GameState(board.getColumns(),board.getRows(),cells,shapeMatrix(externalPiece.getType()),shapeMatrix(controller.getNextPieceType())));}
        int[][] shapeMatrix(TetrominoType value){int[][] coordinates=value.cells(0);int minX=Integer.MAX_VALUE,minY=Integer.MAX_VALUE,maxX=0,maxY=0;for(int[] q:coordinates){minX=Math.min(minX,q[0]);minY=Math.min(minY,q[1]);maxX=Math.max(maxX,q[0]);maxY=Math.max(maxY,q[1]);}int[][] result=new int[maxY-minY+1][maxX-minX+1];for(int[] q:coordinates)result[q[1]-minY][q[0]-minX]=1;return result;}
        void applyExternalMove(ExternalPlayerClient.Move move){if(controller.isGameOver()||controller.getCurrentPiece()!=externalPiece)return;externalTargetRotation=Math.floorMod(move.opRotate(),4);int occupiedOffset=Integer.MAX_VALUE;for(int[] q:externalPiece.getType().cells(externalTargetRotation))occupiedOffset=Math.min(occupiedOffset,q[0]);externalTargetColumn=move.opX()-occupiedOffset;externalActionDelay=.40;}
        void advanceExternalMove(double elapsed){if(externalTargetRotation==null||externalTargetColumn==null||controller.getCurrentPiece()!=externalPiece)return;externalActionDelay-=elapsed;if(externalActionDelay>0)return;externalActionDelay=.13;Tetromino piece=controller.getCurrentPiece();if(piece.getRotation()!=externalTargetRotation){controller.rotateClockwise();return;}if(piece.getColumn()<externalTargetColumn){controller.moveRight();return;}if(piece.getColumn()>externalTargetColumn){controller.moveLeft();return;}/* Once aligned, normal GameController gravity performs the descent. */}
        public void onScoreChanged(int score,int lines){updateLabels();}
        public void onGameOver(int score){updateLabels();status.setText(name+" game over: "+score);HighScoreRepository repository=new HighScoreRepository();if(repository.qualifies(score)){TextInputDialog dialog=new TextInputDialog(name);dialog.setHeaderText("New top-ten score: "+score);dialog.setContentText("Player name:");dialog.showAndWait().map(String::trim).filter(v->!v.isBlank()).ifPresent(v->{try{repository.add(new HighScore(v,score));}catch(java.io.IOException e){new Alert(Alert.AlertType.ERROR,"Could not save score: "+e.getMessage()).showAndWait();}});}}
        void close(){if(external!=null)external.close();}
        void render(){GraphicsContext g=canvas.getGraphicsContext2D();GameBoard b=controller.getBoard();double cell=canvas.getWidth()/b.getColumns();g.setFill(Color.rgb(18,18,22));g.fillRect(0,0,canvas.getWidth(),canvas.getHeight());for(int r=0;r<b.getRows();r++)for(int c=0;c<b.getColumns();c++){TetrominoType t=b.getCell(r,c);if(t!=null)draw(g,t,c,r,cell);g.setStroke(Color.rgb(50,50,58));g.strokeRect(c*cell,r*cell,cell,cell);}Tetromino p=controller.getCurrentPiece();if(p!=null&&!controller.isGameOver())for(int[] q:p.getCells()){double rr=p.getRow()+q[1]+controller.getFallProgress();if(rr>=0)draw(g,p.getType(),p.getColumn()+q[0],rr,cell);}if(controller.isPaused()||controller.isGameOver()){g.setFill(Color.rgb(0,0,0,.65));g.fillRect(0,0,canvas.getWidth(),canvas.getHeight());g.setFill(Color.WHITE);g.setFont(Font.font(24));g.setTextAlign(TextAlignment.CENTER);g.fillText(controller.isPaused()?"PAUSED":"GAME OVER",canvas.getWidth()/2,canvas.getHeight()/2);}}
        void draw(GraphicsContext g,TetrominoType t,double c,double r,double s){g.setFill(t.getColor());g.fillRoundRect(c*s+1,r*s+1,s-2,s-2,4,4);g.setStroke(t.getColor().brighter());g.strokeRoundRect(c*s+2,r*s+2,s-4,s-4,3,3);}
    }
}
